### ISSUE TITLE
Safari web browser functionality

### ISSUE THREAD

**Issue by chief-1buk** [brianshea2/addr.tools#11]
The dnscheck tool is not functioning properly in Safari web browser version 16.1. While the dnscheck produces results for the IP address, DNS resolvers are not given, and show "error occurred".

anyone know whats causing this and how I can resolve it?

Thanks,
![DNS_check-2](https://github.com/user-attachments/assets/9e5e0020-7d38-498a-99d3-96ed0c52fd70)

**Comment by brianshea2** [comment]
Only in Safari? Does it fail almost immediately or after some seconds? Anything relevant in the javascript console (in Safari dev tools)?

**Comment by brianshea2** [comment]
Safari 16.1 is over two years old...

**Comment by chief-1buk** [comment]
is that the problem?

**Comment by chief-1buk** [comment]
> Only in Safari? Does it fail almost immediately or after some seconds? Anything relevant in the javascript console (in Safari dev tools)?

Fails after a minute or less, unsure whats in the javascript console or how to diagnose that.

**Comment by chief-1buk** [comment]
![javascript_DNScheck](https://github.com/user-attachments/assets/f084eb46-6c48-4870-9118-3f91c45dccc3)

**Comment by chief-1buk** [comment]
![Uploading javascript log.jpg…]()

**Comment by chief-1buk** [comment]
![javascript log](https://github.com/user-attachments/assets/13a2e34f-51a5-4c47-b1f1-00dd684e43e7)

**Comment by brianshea2** [comment]
Thanks for the logs. Yes, the oldness of that version is to blame. I only aim to support the most modern browsers, makes writing the tool more fun 😊. `AbortSignal.any` is one such modern feature that isn't available in that version.

Side note in case you don't know, it's a huge security concern to be using such an old browser.

**Comment by chief-1buk** [comment]
> Thanks for the logs. Yes, the oldness of that version is to blame. I only aim to support the most modern browsers, makes writing the tool more fun 😊. `AbortSignal.any` is one such modern feature that isn't available in that version.
> 
> Side note in case you don't know, it's a huge security concern to be using such an old browser.

oh, ok. The problem is my macbook has reached the end of it's update life and is limited to Big Sur OS and nothing more including the Safari browser (AFAIK) update. So, until I can upgrade to a newer mac, I will use chrome or other browsers and NOT Safari. Thank you very much, appreciate it.
