### ISSUE TITLE
Bugzilla input request

### ISSUE THREAD

**Issue by toothlessgodzilla** [brianshea2/addr.tools#3]
@brianshea2

Hello. Can you please reply to this question about dnscheck.tools on Bugzilla? https://bugzilla.mozilla.org/show_bug.cgi?id=1900481#c10 (I'm not involved in this technical discussion).

**Comment by brianshea2** [comment]
Hey! No problem. I don't have a Mozilla bugzilla account, and don't really feel like making one, so I'll reply here and feel free to link or copy/paste.

Relevant code is here: https://github.com/brianshea2/addr.tools/blob/main/website/dnscheck.tools/main.js#L359

The dns resolution time is really the average time it takes for your browser to issue a request (`fetch`) to a non-existent domain and fail that request (rejected promise), hopefully by receiving NXDOMAIN via DNS resolution.
