### ISSUE TITLE
Why SHA-224?

### ISSUE THREAD

**Issue by rmbolger** [brianshea2/addr.tools#5]
Recently stumbled across this fun project and thought I'd try adding a DNS plugin to my ACME client for use with challenges.addr.tools. But the SHA-224 req is slowing me down because my client is PowerShell/.NET based and apparently there's no native implementation. So I'll either have to use a third party library or make my own SHA-224 implementation.

In any case, just curious why you chose SHA-224 over something more commonly implemented like SHA-256.

**Comment by brianshea2** [comment]
Sha256 is too long to fit in a domain label :)

Get-FileHash doesn't support Sha224? That's a shame.

**Comment by PanForPancakes** [comment]
How about using part of more typical SHA-256?

**Comment by brianshea2** [comment]
That would be an improper use of the hashing algorithm and a security concern :)

**Comment by brianshea2** [comment]
If locally calculating the hash proves too difficult, there's this: 

> A GET, POST, or PUT to `https://challenges.addr.tools` with only `secret=<secret>` specified responds with body `<sha224>.challenges.addr.tools` and makes no update.

**Comment by rmbolger** [comment]
That makes perfect sense.

But yeah, `Get-FileHash` is limited to the algorithms supported by the underlying .NET primitives. And those primitives are annoyingly lacking (though getting better slowly over time).

The secret-only request will totally work as a quick solution. Thanks for that nugget. I’ll probably end up toying around with making a native sha-224 implementation anyway for fun.

**Comment by brianshea2** [comment]
Would love to hear how it goes and if/when you get the service working with your Posh-ACME.

**Comment by brianshea2** [comment]
Thank you for adding the service to your tool! And yes, perfectly fine to use the DELETE to clean up. It's not strictly necessary since the challenge records are automatically removed after a few minutes, and it's left off the documentation only for simplicity.
