### ISSUE TITLE
Word wrap DNS check results to avoid horizontal scrolling

### ISSUE THREAD

**Issue by emeritaacuity0u** [brianshea2/addr.tools#7]
When viewing DNS check results on dnscheck.tools, long lines are displayed without word wrapping, causing the need for horizontal scrolling. This makes it difficult to view the output as it doesn’t mimic the behavior expected in a typical terminal environment, where lines are wrapped within the viewport.

Proposed Solution:
Enable word wrap for DNS check results. This would make the output easier to read, especially for results with long lines, and enhance the user experience by eliminating horizontal scrolling.

Expected Outcome:
- DNS check results wrap within the viewport.
- Improved readability and usability on different screen sizes.

Additional Context:
Implementing this change would align with standard terminal behaviour, where word wrapping is often used to keep all content visible without requiring horizontal navigation.

**Comment by brianshea2** [comment]
made some adjustments. how's it now?

**Comment by emeritaacuity0u** [comment]
Spot on, I love it!
